My first commit
Porestoranam/Review_1_python pull request #1
Opened 2019-03-20 11:34 UTC by Porestoranam

first attemp

2019-03-21 10:19 UTC, WokinShopash commented
Проверка глупыми тестами пройдена успешно, в код буду смотреть после субботы.

2019-03-31 08:43 UTC, WokinShopash requested changes

2019-03-31 08:43 UTC, WokinShopash commented on encode_and_decode.py
> +def new_char(char, shift):      # make new char using value of shift
Лучше такие комментарии писать как docstring, на строчке сразу после объявления

2019-03-31 08:43 UTC, WokinShopash commented on encryptor.py
> +            output = open(args.output_file, 'w')
Избавься от дублирования кода, отвечающего за чтение/запись

2019-03-31 08:43 UTC, WokinShopash commented on hack_and_train.py
> +def new_char(char, shift):      # make new char with using value of shift
Можно эту функцию тоже заимпортить из соседнего файла. Но дублировать точно не надо

2019-03-31 08:43 UTC, WokinShopash commented on hack_and_train.py
> +    dic['length'] = 0
Разве значение этого ключа ключа где-то потом используется?

2019-03-31 08:43 UTC, WokinShopash commented on hack_and_train.py
> +    length = len(main_string)
Если такой знаменатель брать, то сумма столбцов будет не 1

2019-03-31 08:43 UTC, WokinShopash commented on hack_and_train.py
> +    ans = 106.0
Какая-то магическая константа

2019-04-06 19:28 UTC, Porestoranam commented on encode_and_decode.py
> +def new_char(char, shift):      # make new char using value of shift
Все комментарии перенесены в docstring для каждой функции.

2019-04-06 19:29 UTC, Porestoranam commented on encryptor.py
> +            output = open(args.output_file, 'w')
Сделано. Теперь код, отвечающий за чтение и запись находится только в одном месте.

2019-04-06 19:30 UTC, Porestoranam commented on hack_and_train.py
> +def new_char(char, shift):      # make new char with using value of shift
Заимпорчено:)

2019-04-06 19:30 UTC, Porestoranam commented on hack_and_train.py
> +    dic['length'] = 0
Действительно, не используется, спасибо!:)

2019-04-06 19:31 UTC, Porestoranam commented on hack_and_train.py
> +    length = len(main_string)
Да, были учтены абсолютно все символы, даже те, которые не являются буквами. Исправлено.

2019-04-06 19:32 UTC, Porestoranam commented on hack_and_train.py
> +    ans = 106.0
Это просто максимальная граница, которая возможна. Всего различных букв получается 52, отклонение каждой из которых по модулю не больше 2. Поставил sys.maxsize

2019-04-06 19:39 UTC, Porestoranam commented
Синтаксические неточности исправлены:)

2019-04-14 15:34 UTC, Porestoranam commented
Counter and str.join included. Double code corrected

2019-04-14 16:28 UTC, WokinShopash requested changes

2019-04-14 16:28 UTC, WokinShopash commented on hack_and_train.py
> +    """get all strings we can"""
Ууу, даже если забыть про то, что мы на паре выяснили, что проходиться можно всего 2 раза вместо 27, 
хранить все варианты раскодирования - ну ооочень затратно

2019-04-14 16:28 UTC, WokinShopash commented on encode_and_decode.py
> +        new_ord = (ord_char - ord('A') + shift) % 26 + ord('A')
26 - магическая константа, которая должна быть унесена куда-то наверх, объявлена один раз с хорошим именем и использована везде в других местах
А еще лучше вычислить ее с помощью того же модуля string

2019-04-14 16:28 UTC, WokinShopash commented on encode_and_decode.py
> +    dis_from_cap_a = ord_char - ord('A')
Какой смысл загонять эти выражения в отдельные переменные, если потом используешь их только по одному разу через 3 строчки в условии, не особо уменьшив количество символов. 
Учитывая, что св питоне можно писать конструкции вида a < b < c, так это и вовсе становится ненужным

2019-04-14 16:28 UTC, WokinShopash commented on hack_and_train.py
> +    allocation_for_string = collections.Counter(ch for ch in main_string if ch in string.ascii_letters)
Пожалуй, строчные и заглавные буквы мы тут хотим считать в одной куче. заглавных в обычном слишком мало, чтобы они дали какую-то хорошую статистику

2019-04-14 16:28 UTC, WokinShopash commented on hack_and_train.py
> +def count_ideal_allocation(text_for_train):
Эта функция абсолютно такая же, как count_approximate
Дублирование кода, печалька

2019-04-14 16:28 UTC, WokinShopash commented on hack_and_train.py
> +def make_dict_of_strings_and_values(main_string, ideal_allocation):
Делать большие строчки ключами словаря - плохая идея.
Поиск по такому словарю сначала проверяет равенство хешей, а потом посимвольное равенство строк, которое займет еще O(длина_текста) времени.

Да и вообще, зачем считать заранее все разницы с эталоном для всех вариантов сдвига? На лету же можно минимум обновлять. 
Если тебе хочется разделить генерацию текста, подсчет разницы с эталоном на разные функции, напиши генераторы.

2019-04-14 16:28 UTC, WokinShopash commented on hack_and_train.py
> +    ans = sys.maxsize
Лучше даже float("inf") - бесконечность в самом что ни на есть классическом понимании

2019-04-17 14:16 UTC, Porestoranam commented on hack_and_train.py
> +    """get all strings we can"""
Исправлено. Да, спасибо, действительно, алгоритмически лучше, да и кода получилось меньше)

2019-04-17 14:16 UTC, Porestoranam commented on encode_and_decode.py
> +        new_ord = (ord_char - ord('A') + shift) % 26 + ord('A')
Сделано

2019-04-17 14:16 UTC, Porestoranam commented on encode_and_decode.py
> +    dis_from_cap_a = ord_char - ord('A')
И в правду, только лишний код:)

2019-04-17 14:17 UTC, Porestoranam commented on hack_and_train.py
> +    allocation_for_string = collections.Counter(ch for ch in main_string if ch in string.ascii_letters)
Теперь все буквы считаются маленькими и по ним идет апроксимация

2019-04-17 14:18 UTC, Porestoranam commented on hack_and_train.py
> +def count_ideal_allocation(text_for_train):
Лучше было вообще убрать эти функции, поскольку для реализации алгоритмически выгодного варианта, они только мешают)

2019-04-17 14:18 UTC, Porestoranam commented on hack_and_train.py
> +def make_dict_of_strings_and_values(main_string, ideal_allocation):
Убрал)

2019-04-17 14:18 UTC, Porestoranam commented on hack_and_train.py
> +    ans = sys.maxsize
Дас)

2019-04-21 16:40 UTC, WokinShopash requested changes

2019-04-21 16:40 UTC, WokinShopash commented on hack_and_train.py
> +def count_ideal_allocation(text_for_train):
Как-то ты не убрал их в итоге.
Смотри, логика того, как считается частота, у тебя сейчас встречается дважды. Надо, чтобы было один раз.

2019-04-21 16:40 UTC, WokinShopash commented on hack_and_train.py
> +    ans_text = []
А с это места здесь с точностью до названий переменных скопирован код ф-ции caesar_encode_string

2019-04-21 16:40 UTC, WokinShopash commented on encryptor.py
> +    if args.text_file is not None:
Сейчас эта логика точь-в-точь повторяет логику чтения на строке 37.
Надо бы сделать это отдельной функцией.

2019-04-21 16:40 UTC, WokinShopash commented on encryptor.py
> +        output = open(args.output_file, 'w')
Вся запись в файл может делаться только под with

2019-04-21 16:40 UTC, WokinShopash commented on encryptor.py
> +    pickle.dump(allocation_in_model, open(args.model_file, 'wb'))
Вся запись в файл может делаться только под with

2019-04-21 16:40 UTC, WokinShopash commented on encryptor.py
> +
Надо избавиться от кода в глобальном namespace. Весь логический код должен быть разделен на функции
Создать функцию для определения и считывания аргументов (get_args), и функция для выполнения логики (main).
Потом последовательно вызвать с помощью `__name__`-проверки, как вот тут:
https://github.com/WokinShopash/FlaskDemoLazyStudents/blob/master/main.py#L93

2019-05-09 17:54 UTC, Porestoranam commented on hack_and_train.py
> +    ans_text = []
Точно)

2019-05-09 19:35 UTC, Porestoranam commented on encryptor.py
> +    pickle.dump(allocation_in_model, open(args.model_file, 'wb'))
fixed

2019-05-09 19:35 UTC, Porestoranam commented on encryptor.py
> +        output = open(args.output_file, 'w')
fixed

2019-05-09 19:36 UTC, Porestoranam commented on encryptor.py
> +
Выделил функцию, теперь мэйн выполняет логику

2019-05-09 19:41 UTC, Porestoranam commented on encryptor.py
> +    if args.text_file is not None:
Сделано)

2019-05-18 17:25 UTC, WokinShopash approved these changes
Зачтено.

2020-03-11 16:59 UTC, merged